//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skypeRobotController_Slave.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magabot didn\'t hear you...\r\nIt isn\'t connected yet.")]
        public string failedToSendMessage {
            get {
                return ((string)(this["failedToSendMessage"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6969")]
        public int port {
            get {
                return ((int)(this["port"]));
            }
            set {
                this["port"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hello!  \nPlease wait until we give you the control of the robot.")]
        public string welcomeMessage {
            get {
                return ((string)(this["welcomeMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You\'re not controlling Magabot yet. \nWait for you turn...")]
        public string waitMessage {
            get {
                return ((string)(this["waitMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Hurray!!! 
Magabot is now under your command. 
Remember: 
You have two ways of controlling the robot
Using chat messages :
- '1' to Assisted Navigation    
  - 'w' to go forward 
  - 's' to go backward
  - 'a' to go left
  - 'd' to go right
  - 'p' to stop
- '2' to Autonomous navigation

Using dial pad
-'*' to Assisted Navigation
  -'2' to go forward
  -'8' to go backward
  -'4' to go left
  -'6' to go right
  -'5' to stop
-'#' to Autonomous navigation")]
        public string controllerMessage {
            get {
                return ((string)(this["controllerMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Hello, \nYou\'ve been selected as my admin\"")]
        public string adminMessage {
            get {
                return ((string)(this["adminMessage"]));
            }
        }
    }
}
